[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Thal_defaults.x",
]
runner = "blash --port COM7 --monitor-baud 2000000 --"

[build]
target = "riscv32imac-unknown-none-elf"

[alias]
flash = ["--color=always", "blflash", "--release", "--port=COM7"]
